version: '3.7'

services:
  bravo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - bravo-db

  bravo-db:
    image: mongo:4.2.9
    command: mongod --port 27117
    ports:
        - 27117:27117
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
